AWSTemplateFormatVersion: '2010-09-09'
Description: 'Despliegue de Instancia EC2 y Bucket S3 para el proyecto DevOps'

Resources:
  # 1. Bucket S3 con versionado y nombre dinámico
  DevOpsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      # Usamos !Sub para que el nombre sea único usando el ID de la cuenta
      BucketName: !Sub 'devops-bucket-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

  # 2. Instancia EC2
  DevOpsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: LabInstanceProfile
      # Esta línea busca automáticamente la última AMI de Amazon Linux 2023
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
      Tags:
        - Key: Name
          Value: DevOps-CloudFormation-Instance

Outputs:
  InstanceID:
    Description: "ID de la instancia EC2 creada"
    Value: !Ref DevOpsInstance
  BucketName:
    Description: "Nombre del bucket S3 creado"
    Value: !Ref DevOpsBucket